name: 'Setup environment for Windows'

runs:
  using: "composite"
  steps:
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v10.6
      with:
        vcpkgGitCommitId: ${{env.VCPKG_COMMIT}}
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0
      with:
        version: 6.4.1