name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:    
  test-clang:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/build
      with:
        configure-flags: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  test-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
  release:
    runs-on: windows-latest
    needs: [test-msvc, test-clang]
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/build
    - name: Zip
      run: Compress-Archive install/* autosweeper.zip
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        files: autosweeper.zip
